### ISSUE TITLE
searcher.py assumes that topics and qrels are in the respective topics and qrels folders

### ISSUE THREAD

**Issue by cmacdonald** [osirrc/jig#84]
So I cannot do e.g. `python run.py search --topics /arbitrary/path/to/topics`

**Comment by r-clancy** [comment]
The `jig` should be able to support this, it can accept relative and absolute paths.

I'm able to run `python run.py search --repo atire --output out/atire --qrels qrels/qrels.robust2004.txt --topic /home/ryan/sync/git/jig/topics/topics.robust04.txt --collection robust04 --top_k 100` without issues (note the mixed relative and absolute paths).

**Comment by cmacdonald** [comment]
You always mount `TOPIC_PATH_HOST = os.path.abspath("topics")` into the guest.

Try using a filename that doesnt match what is in the `topics/` folder i.e. `--topic /home/ryan/sync/git/jig/topics/my.own.topics.txt `

**Comment by r-clancy** [comment]
Ahh, I see what you mean now. I can make a change so that the `jig` mounts the directory the topic file is in.

For example, you'd pass `--topic /home/ryan/sync/ir/topics/mytopic` and the `jig` would:
- mount `/home/ryan/sync/ir/topics` at `/input/topics` in the Docker container
- pass `"topic": {"path": "/input/topics/mytopic", "format": "trec"}` in the JSON to the `search` hook

Seem reasonable?

**Comment by cmacdonald** [comment]
Agreed, looks better!

**Comment by r-clancy** [comment]
Fixed in #86
